management:
  context-path: /manage
  security:
    enabled: false

server:
  port: 8888
  tomcat:
    max-connections: 60000
    accept-count: 100
    max-threads: 200

service:
  response:
    duration: 100
    deviation: 0